# Generated by Django 4.1.4 on 2022-12-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_code_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
